# netlify.toml  – static site, no build step
# ------------------------------------------
[build]
  publish = "."            # serve the repo root
  command = ""             # no build

# CORS + long-term cache for glb files (optional but useful)
[[headers]]
  for = "/assets/3D/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

# Basic security headers for all routes (optional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options  = "DENY"
    X-XSS-Protection = "1; mode=block"