# Netlify configuration – publish the “assets” folder
# Netlify configuration – publish the “assets” folder
[build]
  command = ""        # no build step
  publish = "assets"  # deploy the /assets directory