# Wi-Fi and MQTT settings for Simulation
wifi:
  ssid: "SimulatedNetwork"
  password: "SimulatedPassword"
mqtt:
  broker: "localhost"  # Use localhost for simulation
  port: 1883
  client_id: "visionvend_controller"
  unlock_topic: "case/123/cmd"
  status_topic: "case/123/status"
  door_topic: "case/123/door"
  hmac_secret: "simulation_secret_key"

# LTE settings (Simulated)
lte:
  apn: "sim_apn"

# Stripe API (Simulated)
stripe:
  api_key: "sk_test_simulation_key"

# Server settings
server:
  host: "0.0.0.0"
  port: 5000
  url: "http://localhost:5000"

# Camera settings
camera:
  resolution: [1280, 720]
  framerate: 30
  storage_path: "/sd/videos"

# Training and auto-labeling
training:
  dataset_path: "/sd/datasets"
  model_path:   "/sd/models/rtdetr.pt"
  base_model:   "rtdetr-l.pt"
  min_frames:   60
  # --- auto-label knobs ---
  autolabel:
    min_area:      5000      # lowest px² we still consider a product
    max_area:      0.6       # fraction of frame
    stable_frames: 5
    save_aug:      true
    hand_iou_max:  0.35      # if bounding-box overlaps hand >35 % we shrink it
    history:       400       # MOG2 history for background subtraction
    varThreshold:  40        # MOG2 varThreshold
    cam_ids:       [0, 1]    # Camera device IDs (top-down, bottom-up)
    restock_pin:   27        # GPIO pin for RESTOCK button
    led_pin:       23        # GPIO pin for RGB LED feedback
    led_green:     [0,255,0] # RGB for success
    led_red:       [255,0,0] # RGB for error
    timeout_sec:   15        # Max seconds to wait for operator
    log_path:      "/sd/autolabel_log.jsonl" # Where to write logs


# Hardware pins (ESP32-S3)
pins:
  mosfet: 26
  hall_sensor: 27
  hx711_sck: 14
  hx711_dt: 15
  oled_sda: 19
  oled_scl: 18
  neopixel: 23
  buzzer: 25
  tof_sda: 21
  tof_scl: 22
  pi_signal: 16

# Inventory mapping
inventory:
  cola: {weight: 355, tolerance: 5, price: 2.00}
  chips: {weight: 70, tolerance: 4, price: 1.50}

# Lock settings
lock:
  timeout: 10

# Feedback settings
feedback:
  languages: ["en"]
