# VisionVend CI

# This workflow will run tests (if present) on push and pull request to main branches
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Run tests
        run: |
          if [ -d tests ]; then pytest; else echo "No tests yet"; fi
